### ISSUE TITLE
Peak detection and marching cubes?

### ISSUE THREAD

**Issue by jo-mueller** [guiwitz/napari-skimage#3]
Hi @guiwitz ,

Would you be interested in having the `peak_local_max` as well as the `marching_cubes` algorithms within this project? I don't think I've seen it implemented often elsewhere and I think they are quite useful to transition more easily between `image` layers > `points` layer as  well as `Labels` layers > `Surface` layers.

From a menu perspective, I would put them into the following places:

```
Layers
  - Layer Type
    - Detect local maxima (returns points layer)
    - Marching cubes (returns surface layer)
```

With the structure you have already provided I don't think it should be a lot of effort to implement - let me know what you think :)

**Comment by guiwitz** [comment]
Hi @jo-mueller, these two functions would definitely fit very well in the project, and would be great way to show case different outputs of different types that images and labels. A PR would be very wellcome!
